channels:
- conda-forge
dependencies:
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- ipython
- matplotlib =3.7.1
- numpy =1.24.3
- pyiron_base =0.5.38
- pyiron_atomistics =0.2.67
- pyparsing =3.0.9
- scipy =1.10.1
- seaborn =0.12.2
- scikit-image =0.19.3
- randspg =0.0.1
- boto3 =1.26.137
- moto =4.1.10
- pycp2k =0.2.2
- typeguard =4.0.0
- aws-sam-translator =1.65.0
- python >= 3.10
- lammps
